### ISSUE TITLE
nn报错

### ISSUE THREAD

**Issue by xuexinxiansheng** [yjrqz777/ql#1]
![image](https://github.com/yjrqz777/ql/assets/63955913/6d5b506e-6445-41f3-a0cb-e6725ca7d23c)

**Comment by yjrqz777** [comment]
请自行百度，脚本正常，猜测环境问题或者环境变量名称错误

**Comment by xuexinxiansheng** [comment]
我就单拉了这一个文件，还要拉其他辅助文件吗

**Comment by yjrqz777** [comment]
请自行百度，脚本正常，猜测环境问题或者环境变量名称错误，我的环境为linux，并非安卓，个别问题请自行解决，单文件可以运行，需要request依赖

**Comment by yjrqz777** [comment]
这个报错很明了了，就是你这个变量问题，可以尝试直接添加变量，并非添加环境变量

**Comment by xuexinxiansheng** [comment]
![image](https://github.com/yjrqz777/ql/assets/63955913/62620c1a-878e-4e70-8e27-0deddfc474dc)
这里说要在代码改，我没添加环境变量，就在代码里直接把nn_**的部分替换了，我在服务器加docker青龙跑的，环境和依赖都装了，我再尝试尝试吧

**Comment by yjrqz777** [comment]
第一次回你就你说了，可能是环境变量的问题，改回原来代码，添加环境变量就好了

**Comment by xuexinxiansheng** [comment]
已经好了，用环境变量就可以，直接改代码不行，非常感谢！

**Comment by yjrqz777** [comment]
环境变量
